---
- name: Update rundeck-config.properties
  template:
    src: "../templates/etc/rundeck/rundeck-config.properties.j2"
    dest: /etc/rundeck/rundeck-config.properties
    mode: 0640
    owner: rundeck
    group: rundeck
    backup: no
- name: Remove keystore (if exists)
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/rundeck/ssl/keystore
    - /etc/rundeck/ssl/truststore
    - /etc/rundeck/ssl/keystore.p12
- name: Create a pkcs12 keystore
  command: "openssl pkcs12 -export -name rundeck -in /etc/pki/tls/certs/{{ ansible_fqdn | replace('.', '_') }}.crt -inkey /etc/pki/tls/private/{{ ansible_fqdn | replace('.', '_') }}.key -out /etc/rundeck/ssl/keystore.p12 -passout pass:{{ rundeckstore.defaultstorepassword }}"
# Create PKCS12 keystore from private key and public certificate.
- name: Import PKCS12 keystore and build a keystore and truststore
  command: "keytool -importkeystore -deststorepass {{ rundeckstore.defaultstorepassword }} -destkeypass {{ rundeckstore.defaultstorepassword }} -destkeystore {{ item }} -srckeystore /etc/rundeck/ssl/keystore.p12 -srcstoretype PKCS12 -srcstorepass {{ rundeckstore.defaultstorepassword }} -alias rundeck"
  with_items:
    - /etc/rundeck/ssl/keystore
    - /etc/rundeck/ssl/truststore
- name: Update ssl.properties
  template:
    src: "../templates/etc/rundeck/ssl/ssl.properties.j2"
    dest: /etc/rundeck/ssl/ssl.properties
    mode: 0640
    owner: rundeck
    group: rundeck
    backup: no
