---
- name: Remove keystore (if exists)
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/rundeck/ssl/keystore
    - /etc/rundeck/ssl/truststore
    - /etc/rundeck/ssl/keystore.p12
- name: Create a pkcs12 keystore
  shell: "openssl pkcs12 -export -name rundeck -in /etc/pki/tls/certs/{{ ansible_fqdn | replace('.', '_') }}.crt -inkey /etc/pki/tls/private/{{ ansible_fqdn | replace('.', '_') }}.key -out /etc/rundeck/ssl/keystore.p12 -passout pass:{{ rundeckstore.defaultstorepassword }}"
# Create PKCS12 keystore from private key and public certificate.
- name: Import PKCS12 keystore and build a keystore and truststore
  shell: "keytool -importkeystore -deststorepass {{ rundeckstore.defaultstorepassword }} -destkeypass {{ rundeckstore.defaultstorepassword }} -destkeystore {{ item }} -srckeystore /etc/rundeck/ssl/keystore.p12 -srcstoretype PKCS12 -srcstorepass {{ rundeckstore.defaultstorepassword }} -alias rundeck"
  with_items:
    - /etc/rundeck/ssl/keystore
    - /etc/rundeck/ssl/truststore
- name: Remove PKCS12 file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/rundeck/ssl/keystore.p12
- file:
    path: "{{ item }}"
    owner: rundeck
    group: rundeck
    mode: 0644
  with_items:
    - /etc/rundeck/ssl/keystore
    - /etc/rundeck/ssl/truststore
- name: Update rundeck-config.properties
  template:
    src: "../templates/etc/rundeck/rundeck-config.properties.j2"
    dest: /etc/rundeck/rundeck-config.properties
    mode: 0640
    owner: rundeck
    group: rundeck
    backup: no
- name: Update ssl.properties
  template:
    src: "../templates/etc/rundeck/ssl/ssl.properties.j2"
    dest: /etc/rundeck/ssl/ssl.properties
    mode: 0640
    owner: rundeck
    group: rundeck
    backup: no
- name: Get the uuid
  shell: "sed '/^\#/d' /etc/rundeck/framework.properties | grep 'rundeck.server.uuid' | sed 's/^.*=\s//'"
  register: uuid_result
# - set_fact:
#    rundeck_server_uuid: "{{ lookup('ini', 'rundeck.server.uuid type=properties file=/etc/rundeck/framework.properties') }}"
- debug: msg="{{ uuid_result }}"
- name: Update framework.properties
  template:
    src: "../templates/etc/rundeck/framework.properties.j2"
    dest: /etc/rundeck/framework.properties
    mode: 0640
    owner: rundeck
    group: rundeck
    backup: no
- name: Update Environment variables to turn SSL on
  template:
    src: "../templates/etc/sysconfig/rundeckd.j2"
    dest: /etc/sysconfig/rundeckd
    mode: 0644
    backup: no
