---
- hosts: "{{ target_hosts }}"
  vars_files:
    - ./vars/main.yml
  tasks:
    - name: Include Fedora specific tasks
      include_tasks: fedora.yml
      when: ansible_distribution == 'Fedora'
    - name: Include RHEL specific tasks
      include_tasks: rhel.yml
      when: ansible_distribution == 'Red Hat Enterprise Linux' and ansible_lsb.major_release|int <= 7
      