---
- hosts: "{{ target_hosts }}"
  vars_files:
    - ./vars/main.yml
  tasks:
  - name: Add Some repo
    yum_repository:
      name: "{{ rundeckrepo.name }}"
      description: "{{ rundeckrepo.name }}"
      baseurl: "{{ rundeckrepo.baseurl }}"
      gpgkey: http://server.com/keys/somerepo.pub
      gpgcheck: "{{ rundeckrepo.gpgcheck }}"
      repo_gpgcheck: "{{ rundeckrepo.repo_gpgcheck }}"
      enabled: "{{ rundeckrepo.enabled }}"
    - name: Include Fedora specific tasks
      include_tasks: fedora.yml
      when: ansible_distribution == 'Fedora'
    - name: Include RHEL specific tasks
      include_tasks: rhel.yml
      when: ansible_distribution == 'Red Hat Enterprise Linux' and ansible_lsb.major_release|int <= 7
      