---
- hosts: "{{ target_hosts }}"
  vars_files:
    - ./vars/main.yml
  tasks:
    - name: Setup the RunDeck via YUM/DNF
      include_tasks: setup.yml
      tags:
        - deploy
    - name: Restart and enable if needed
      service:
        name: rundeckd
        state: restarted
        enabled: yes
      tags:
        - deploy 