---
- src: ssh://git@github.com/USF-IT/cims-ansible-inventory.git
  version: develop
  scm: git
  name: inventory
- src: ssh://git@github.com/USF-IT/idm-ansible-common.git
  version: develop
  scm: git
  name: common
- src: ssh://git@github.com/USF-IT/cims-ansible-role-certtool.git
  version: develop
  scm: git
  name: certtool
- src: jdauphant.nginx
  version: v2.6
  name: nginx
  nginx_http_params:
    - sendfile "on"
    - tcp_nopush "on"
    - tcp_nodelay "on"
    - keepalive_timeout "65"
    - access_log "/var/log/nginx/access.log"
    - error_log "/var/log/nginx/error.log"
    - server_tokens off
    - types_hash_max_size 2048
    - client_max_body_size "3M"
- src: geerlingguy.repo-epel
  version: 1.2.1
  name: repo-epel
