---
- name: install jdk 8
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
- name: Add Rundeck Repo
  yum_repository:
    name: "{{ rundeckrepo.name }}"
    description: "{{ rundeckrepo.name }}"
    baseurl: "{{ rundeckrepo.baseurl }}"
    gpgcheck: "{{ rundeckrepo.gpgcheck }}"
    repo_gpgcheck: "{{ rundeckrepo.repo_gpgcheck }}"
    enabled: "{{ rundeckrepo.enabled }}"
- name: install the latest version of rundeck
  package:
    name: rundeck
    state: latest
